server:
  path: localhost
  port: 8080
postgres:
  connect_timeout: 200
  pg_server:
    path: localhost
    port: 6543
  user: postgres
  password: qwerty1234
  db: auth
loglevel: 0
server_timeout: 500