server:
  path: localhost
  port: 8080
postgres:
  connect_timeout: 200
  pg_server:
    path: localhost
    port: 5432
  user: postgres
  password: password
  db: auth-service
loglevel: 0
server_timeout: 500
email: mail.you@gmail.com
